### ISSUE TITLE
need of `require common_models/`

### ISSUE THREAD

**Issue by joaobrittoneto** [rock-core/bundles-common_models#7]
I was trying to update our project for using the common_models, but got the follow error:
`uninitialized constant CommonModels::Services::JointsOpenLoopController`

I could track the problem to the lack of `common_models/` in front of the [requires](https://github.com/rock-core/bundles-common_models/blob/master/models/services/control_loop.rb#L1).
Looks like if bundlesA depends on bundlesB, and both have the same files name (e.g. `/models/services/controller.rb`), the require could not distinguish between the right bundles.

I am not sure if the require should/ could look for the file only in the bundles folder, or if specifying  the bundles' name in front of the requires is the best solution.

**Comment by doudou** [comment]
Right now, you need to add the common_models explicitely to $LOAD_PATH in `config/init.rb`. I envision that later Roby will get some helpers for this.

For reference, see the bottom of https://doudou.github.io/rock_website/basics/getting_started.html. I would suggest moving the change of `search_path` from the `Robot.init` block into `config/init.rb` though.

**Comment by joaobrittoneto** [comment]
Ok,
I did as proposed, but still didn't work. 

The problem is that adding common_models to $LOAD_PATH doesn't explicitly inform that a `require "models/services/controller.rb"` placed in bundles/common_models should be looked in the `"common_models/models/services/controller.rb"`. Instead it looks in the first paths of the search_path vector.

In the case below, it duplicates the presence of the common_models, but it still look for a file first in bundles/flat_fish, then bundles/dive, and so on. As there is a `dive/models/services/controller.rb`, it will use this file, instead of `common_models/models/services/controller.rb`

Looks like it is more robust to just use the bundles' name in front of the require, or I am missing something?
```
[1] pry(main)> Roby.app.search_path
=> ["/home/joao/dev.bir.alpha/bundles/flat_fish",
 "/home/joao/dev.bir.alpha/bundles/dive",
 "/home/joao/dev.bir.alpha/bundles/gazebo_scenes",
 "/home/joao/dev.bir.alpha/bundles/common_models",
 "/home/joao/dev.bir.alpha/bundles/rock",
 "/home/joao/dev.bir.alpha/bundles",
 "/home/joao/dev.bir.alpha/install/share/rock",
 "/home/joao/dev.bir.alpha/bundles/common_models"]
[2] pry(main)> exit

```

**Comment by doudou** [comment]
The original policy was actually coming from the ability to override an existing model file by your own. This can be traced back to the (really bad) idea of auto-requiring things.

Now that we don't auto-require, I agree that it would make more sense to prepend the bundle name. Would you be willing to do the work in common_models ? Since `common_models` is in any case a "new" bundle, we could decide breaking this. However, we will need to update the documentation as well.

**Comment by joaobrittoneto** [comment]
> Would you be willing to do the work in common_models ?

Done https://github.com/rock-core/bundles-common_models/pull/10

**Comment by doudou** [comment]
PR merged. Thanks !
